"""initial schema

Revision ID: 5d0a8c237c2d
Revises: 
Create Date: 2026-07-12 01:00:00.185360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5d0a8c237c2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for the vector columns below; safe to run on every fresh database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('Free', 'Standard', 'Premium', 'Enterprise', name='customer_tier'), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('preferred_language', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('owning_team', sa.Enum('Technical Support', 'Billing Operations', 'Identity and Access', 'Refunds Team', 'Product Support', 'Security Operations', 'General Support', name='assigned_team'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Beta', 'Deprecated', name='product_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('subscription_status', sa.Enum('Active', 'Trial', 'Expired', 'Cancelled', name='subscription_status'), nullable=False),
    sa.Column('access_status', sa.Enum('Active', 'Inactive', 'Suspended', name='access_status'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_customer_product')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('affected_location', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.Enum('Critical', 'High', 'Medium', 'Low', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Monitoring', 'Resolved', name='incident_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('Email', 'Chat', 'Phone', 'Portal', name='ticket_channel'), nullable=False),
    sa.Column('category', sa.Enum('Technical Issue', 'Billing', 'Account Access', 'Refund', 'Product Query', 'Security', 'Needs Clarification', 'Other', name='ticket_category'), nullable=True),
    sa.Column('priority', sa.Enum('High', 'Medium', 'Low', name='ticket_priority'), nullable=True),
    sa.Column('assigned_team', sa.Enum('Technical Support', 'Billing Operations', 'Identity and Access', 'Refunds Team', 'Product Support', 'Security Operations', 'General Support', name='assigned_team'), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Routed', 'In Progress', 'Needs Human Review', 'Resolved', name='ticket_status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('ai_category', sa.Enum('Technical Issue', 'Billing', 'Account Access', 'Refund', 'Product Query', 'Security', 'Needs Clarification', 'Other', name='ticket_category'), nullable=True),
    sa.Column('ai_priority', sa.Enum('High', 'Medium', 'Low', name='ticket_priority'), nullable=True),
    sa.Column('ai_assigned_team', sa.Enum('Technical Support', 'Billing Operations', 'Identity and Access', 'Refunds Team', 'Product Support', 'Security Operations', 'General Support', name='assigned_team'), nullable=True),
    sa.Column('final_category', sa.Enum('Technical Issue', 'Billing', 'Account Access', 'Refund', 'Product Query', 'Security', 'Needs Clarification', 'Other', name='ticket_category'), nullable=True),
    sa.Column('final_priority', sa.Enum('High', 'Medium', 'Low', name='ticket_priority'), nullable=True),
    sa.Column('final_assigned_team', sa.Enum('Technical Support', 'Billing Operations', 'Identity and Access', 'Refunds Team', 'Product Support', 'Security Operations', 'General Support', name='assigned_team'), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_feedback')
    op.drop_table('tickets')
    op.drop_table('knowledge_documents')
    op.drop_table('incidents')
    op.drop_table('customer_products')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
