"""add auth, profiles, rbac, conversations, assignments, audit, evidence

Revision ID: 793849ed5e84
Revises: 95eace7e8c99
Create Date: 2026-07-12 08:46:07.597664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '793849ed5e84'
down_revision: Union[str, Sequence[str], None] = '95eace7e8c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 'assigned_team', 'ticket_category' and 'ticket_priority' already exist (created by the
# initial-schema migration); every column below that reuses them must pass
# create_type=False so this migration doesn't try to CREATE TYPE a second time.
# 'user_role' is new here but used by two tables in this same migration, so it's created
# once explicitly up front and every column reference also uses create_type=False.
ASSIGNED_TEAM_VALUES = (
    'Technical Support', 'Billing Operations', 'Identity and Access', 'Refunds Team',
    'Product Support', 'Security Operations', 'General Support',
)


def _existing_enum(*values: str, name: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum = postgresql.ENUM('Customer', 'Support Agent', 'Admin', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', _existing_enum('Customer', 'Support Agent', 'Admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', _existing_enum('Customer', 'Support Agent', 'Admin', name='user_role'), nullable=False),
    sa.Column('team', _existing_enum(*ASSIGNED_TEAM_VALUES, name='assigned_team'), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_agent_invitations_email'), 'agent_invitations', ['email'], unique=False)
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('team', _existing_enum(*ASSIGNED_TEAM_VALUES, name='assigned_team'), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.Enum('Available', 'Busy', 'Offline', name='agent_availability'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.Enum('Password Reset', 'Email Verification', name='token_purpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_preferences', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('routing_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('customer_profile_used', sa.Boolean(), nullable=False),
    sa.Column('product_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('active_incident_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('similar_ticket_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('knowledge_document_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('category', _existing_enum('Technical Issue', 'Billing', 'Account Access', 'Refund', 'Product Query', 'Security', 'Needs Clarification', 'Other', name='ticket_category'), nullable=False),
    sa.Column('priority', _existing_enum('High', 'Medium', 'Low', name='ticket_priority'), nullable=False),
    sa.Column('assigned_team', _existing_enum(*ASSIGNED_TEAM_VALUES, name='assigned_team'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('clarification_questions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('routing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('assigned_team', _existing_enum(*ASSIGNED_TEAM_VALUES, name='assigned_team'), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.Enum('Customer Reply', 'Agent Reply', 'Internal Note', name='message_type'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tickets_assigned_agent_id_users', 'tickets', 'users', ['assigned_agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tickets_assigned_agent_id_users', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'assigned_agent_id')
    op.drop_table('ticket_messages')
    op.drop_table('ticket_assignments')
    op.drop_table('routing_evidence')
    op.drop_table('user_sessions')
    op.drop_table('customer_profiles')
    op.drop_table('auth_tokens')
    op.drop_table('audit_events')
    op.drop_table('agent_profiles')
    op.drop_index(op.f('ix_agent_invitations_email'), table_name='agent_invitations')
    op.drop_table('agent_invitations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
