"""add ticket routing_time_ms

Revision ID: 95eace7e8c99
Revises: 5d0a8c237c2d
Create Date: 2026-07-12 07:38:17.263962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eace7e8c99'
down_revision: Union[str, Sequence[str], None] = '5d0a8c237c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('routing_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'routing_time_ms')
    # ### end Alembic commands ###
